In [6]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

arr=np.random.random(size=(5,4,3))
var=tf.Variable(arr)

# 每次都找var[,:,]的最大值
arg_max=tf.arg_max(var,dimension=1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run(var))
    print(sess.run(arg_max))

[[[0.30566661 0.75442717 0.70346823]
  [0.62693678 0.36323518 0.2166906 ]
  [0.76764905 0.79444696 0.44354224]
  [0.41192104 0.42497032 0.23370204]]

 [[0.48948531 0.69378926 0.47286695]
  [0.24034966 0.92642172 0.616362  ]
  [0.20650097 0.07023292 0.44376065]
  [0.59207108 0.90238857 0.25077408]]

 [[0.42354117 0.52235109 0.04037119]
  [0.31704703 0.88657551 0.82507088]
  [0.2235806  0.9868379  0.0099688 ]
  [0.50875481 0.11944391 0.57908306]]

 [[0.41880089 0.00895712 0.72153488]
  [0.58079133 0.07639467 0.72879911]
  [0.6331109  0.09015282 0.98749187]
  [0.55049168 0.3823963  0.09442846]]

 [[0.88549556 0.72241706 0.8874997 ]
  [0.21311255 0.24343345 0.02067351]
  [0.26349418 0.56311437 0.34171727]
  [0.08366377 0.80506536 0.80525724]]]
[[2 2 0]
 [3 1 1]
 [3 2 1]
 [2 3 2]
 [0 3 0]]
