In [36]:
# 可以看到这个玩意不是简单的算准确度，而是叠加地来算准确度，例如下面的第二个结果，就是两次结果的综合准确度
# update 一次才会更新这个准确度，这个操作会更新count和total，从而更新准确度
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
output_arr=np.random.choice([0,1],size=[2,10])
label_arr=np.random.choice([0,1],size=[2,10])

print(output_arr)
print(label_arr)

output_batch=tf.data.Dataset.from_tensor_slices(output_arr).make_one_shot_iterator().get_next()
label_batch=tf.data.Dataset.from_tensor_slices(label_arr).make_one_shot_iterator().get_next()

accuracy,update_op=tf.metrics.accuracy(labels=label_batch,predictions=output_batch)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run([accuracy,update_op]))
    print(sess.run([accuracy,update_op]))
print(np.sum(output_arr==label_arr))

[[0 1 1 0 0 1 1 0 1 1]
 [0 1 0 1 1 1 0 0 1 0]]
[[0 1 1 1 0 0 0 0 0 1]
 [0 1 1 0 0 1 1 0 1 1]]
[0.0, 0.6]
[0.55, 0.6]
11


label
[[0 0 0 0 1 1 0 0 1 1]
 [0 1 1 0 1 0 0 0 0 0]]
output
[[0 1 0 0 1 1 0 0 1 0]
 [1 0 0 0 0 1 1 0 0 0]]
[1.0]
[4.0]


In [35]:
8/20

0.4